/* eslint-disable import/prefer-default-export */
export const mockGenres = {
  genres: [
    { id: 28, name: 'Action' },
    { id: 12, name: 'Adventure' },
    { id: 16, name: 'Animation' },
    { id: 35, name: 'Comedy' },
    { id: 80, name: 'Crime' },
    { id: 99, name: 'Documentary' },
    { id: 18, name: 'Drama' },
    { id: 10751, name: 'Family' },
    { id: 14, name: 'Fantasy' },
    { id: 36, name: 'History' },
    { id: 27, name: 'Horror' },
    { id: 10402, name: 'Music' },
    { id: 9648, name: 'Mystery' },
    { id: 10749, name: 'Romance' },
    { id: 878, name: 'Science Fiction' },
    { id: 10770, name: 'TV Movie' },
    { id: 53, name: 'Thriller' },
    { id: 10752, name: 'War' },
    { id: 37, name: 'Western' },
  ],
}

export const mockMovieQueryResponse = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/tutaKitJJIaqZPyMz7rxrhb4Yxm.jpg',
      genre_ids: [35, 16, 10751, 10402],
      id: 438695,
      original_language: 'en',
      original_title: 'Sing 2',
      overview:
        'Buster and his new cast now have their sights set on debuting a new show at the Crystal Tower Theater in glamorous Redshore City. But with no connections, he and his singers must sneak into the Crystal Entertainment offices, run by the ruthless wolf mogul Jimmy Crystal, where the gang pitches the ridiculous idea of casting the lion rock legend Clay Calloway in their show. Buster must embark on a quest to find the now-isolated Clay and persuade him to return to the stage.',
      popularity: 1761.506,
      poster_path: '/aWeKITRFbbwY8txG5uCj4rMCfSP.jpg',
      release_date: '2021-12-01',
      title: 'Sing 2',
      video: false,
      vote_average: 8.2,
      vote_count: 1764,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [16, 10402],
      id: 653464,
      original_language: 'en',
      original_title: "Let's All Sing Together: No. 2",
      overview:
        "Four popular songs with animated backgrounds, sung by the Four Gentlemen Quartet: Oh Susanna, with a short cartoon sequence of two couples in a square dance, Carry On, Short'nin Bread, and Pack Up Your Troubles.",
      popularity: 2.071,
      poster_path: '/yNkJEjhJg000LKLyA36ucHOz7Rf.jpg',
      release_date: '1944-12-04',
      title: "Let's All Sing Together: No. 2",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: '/z9ft5HYHzWcasR6SGcgeluxTznB.jpg',
      genre_ids: [16, 35, 10751, 10402],
      id: 335797,
      original_language: 'en',
      original_title: 'Sing',
      overview:
        'A koala named Buster recruits his best friend to help him drum up business for his theater by hosting a singing competition.',
      popularity: 196.887,
      poster_path: '/zZTlF2eVVUkbdmccd3bNUU9T9sD.jpg',
      release_date: '2016-11-23',
      title: 'Sing',
      video: false,
      vote_average: 7.1,
      vote_count: 6586,
    },
    {
      adult: false,
      backdrop_path: '/4A6eynbHIRn03F9AugE0hPf8uO9.jpg',
      genre_ids: [35, 18],
      id: 623135,
      original_language: 'ko',
      original_title: 'Sinkhole',
      overview:
        'The average citizen Dong-won and his family move into a house bought after years of hard work. Filled with happiness, he invites his colleagues for a housewarming party, but the heavy rain during the night before creates a gigantic sinkhole, and in a mere minute, it swallows up the whole house and the people inside. Hundreds of meters down the hole, Dong-won, his neighbor Man-su, and the unfortunate guests must find their way out. Rain starts to pour down, filling the sinkhole with water, and they’re running out of time.',
      popularity: 274.88,
      poster_path: '/alBxLvZ5LkDRJPw4TX1PgkWLE8a.jpg',
      release_date: '2021-08-11',
      title: 'Sinkhole',
      video: false,
      vote_average: 7.1,
      vote_count: 36,
    },
    {
      adult: false,
      backdrop_path: '/6A5ugY49ukHmMLaMRwkjaKouzCn.jpg',
      genre_ids: [10749, 35, 18],
      id: 810873,
      original_language: 'en',
      original_title: 'Single All the Way',
      overview:
        'Desperate to avoid his family’s judgment about his perpetual single status, Peter convinces his best friend Nick to join him for the holidays and pretend that they’re now in a relationship. But when Peter’s mother sets him up on a blind date with her handsome trainer James, the plan goes awry.',
      popularity: 67.336,
      poster_path: '/bfZPNzAwUQZ6FZQi1d136KLr3wl.jpg',
      release_date: '2021-12-02',
      title: 'Single All the Way',
      video: false,
      vote_average: 6.5,
      vote_count: 225,
    },
    {
      adult: false,
      backdrop_path: '/9yXPubeQuNzyIdbaUoXAurK40xv.jpg',
      genre_ids: [35, 10749],
      id: 259694,
      original_language: 'en',
      original_title: 'How to Be Single',
      overview:
        'New York City is full of lonely hearts seeking the right match, and what Alice, Robin, Lucy, Meg, Tom and David all have in common is the need to learn how to be single in a world filled with ever-evolving definitions of love.',
      popularity: 30.05,
      poster_path: '/a4Ce3qHqIyHM3QfGsiVTAu3YADJ.jpg',
      release_date: '2016-01-21',
      title: 'How to Be Single',
      video: false,
      vote_average: 6.2,
      vote_count: 2796,
    },
    {
      adult: false,
      backdrop_path: '/54chAMdvhmK1Fh7twaYxbB4ojQB.jpg',
      genre_ids: [878],
      id: 484886,
      original_language: 'en',
      original_title: 'Singularity',
      overview:
        "When Elias van Dorne, CEO of the world's largest robotics company, introduces his most powerful invention, Kronos-a super-computer designed to end all wars-it determines that humans are the biggest threat and launches a worldwide attack on mankind. A small band of survivors must form an unlikely alliance to survive the greatest artificial intelligence threat man will ever know.",
      popularity: 27.41,
      poster_path: '/qmAq1fsprWHhFARdpPz0A46ylUS.jpg',
      release_date: '2017-11-24',
      title: 'Singularity',
      video: false,
      vote_average: 3.6,
      vote_count: 156,
    },
    {
      adult: false,
      backdrop_path: '/ww6f0XEn8aUbNsK1OQGdutJWwQf.jpg',
      genre_ids: [35, 10749, 18, 10402],
      id: 369557,
      original_language: 'en',
      original_title: 'Sing Street',
      overview:
        'A boy growing up in Dublin during the 1980s escapes his strained family life by starting a band to impress the mysterious girl he likes.',
      popularity: 17.343,
      poster_path: '/sUWpVlrvzU2SJbnVZqIeKulPKwk.jpg',
      release_date: '2016-03-11',
      title: 'Sing Street',
      video: false,
      vote_average: 7.9,
      vote_count: 1837,
    },
    {
      adult: false,
      backdrop_path: '/q4T0G4zLS2Q0pkozbDscQe4qL2L.jpg',
      genre_ids: [35, 18, 10749],
      id: 11068,
      original_language: 'en',
      original_title: 'Singles',
      overview:
        "Romantic comedy about six of Seattle's young people, most of whom live in the same apartment building and whose lives revolve around the city's ever-expanding music scene. The interrelated stories about each character's progress through the singles scene are intriguing and often very funny, and the soundtrack is a grunge fanatic's dream, with the likes of Soundgarden, Pearl Jam and Mudhoney.",
      popularity: 11.177,
      poster_path: '/cNM5YW9DgMv5vmLPE1uos1VCI2I.jpg',
      release_date: '1992-09-18',
      title: 'Singles',
      video: false,
      vote_average: 6.4,
      vote_count: 276,
    },
    {
      adult: false,
      backdrop_path: '/l1hFKYKtyOjB9rYIoGqrybLtv5p.jpg',
      genre_ids: [28, 35],
      id: 12273,
      original_language: 'hi',
      original_title: 'Singh Is Kinng',
      overview:
        'A comic caper about Happy Singh, a Punjabi villager who goes through a series of misadventures and eventually becomes the King of the Australian underworld.',
      popularity: 5.595,
      poster_path: '/kYWDpDhKDuGzz3dmxkBiI4LelYN.jpg',
      release_date: '2008-01-01',
      title: 'Singh Is Kinng',
      video: false,
      vote_average: 5.5,
      vote_count: 62,
    },
    {
      adult: false,
      backdrop_path: '/4rHZyoFxGxvkMNiLFEqwm19HCtc.jpg',
      genre_ids: [10749, 18],
      id: 34653,
      original_language: 'en',
      original_title: 'A Single Man',
      overview:
        'The life of George Falconer, a British college professor, is reeling with the recent and sudden loss of his longtime partner. This traumatic event makes George challenge his own will to live as he seeks the console of his close girl friend Charley, who is struggling with her own questions about life.',
      popularity: 14.144,
      poster_path: '/vhoM2LmcPlzcgBIztqqsSAYwaF7.jpg',
      release_date: '2009-10-19',
      title: 'A Single Man',
      video: false,
      vote_average: 7.3,
      vote_count: 1245,
    },
    {
      adult: false,
      backdrop_path: '/zAlmrbAOAEUIFJuGRkCbUPXNbiO.jpg',
      genre_ids: [80, 18],
      id: 42822,
      original_language: 'en',
      original_title: '20,000 Years in Sing Sing',
      overview:
        'Brash hoodlum Tom Connors enters Sing Sing cocksure of himself and disrespectful toward authority, but his tough but compassionate warden changes him.',
      popularity: 6.41,
      poster_path: '/d2y4umnDDS7DkP5S64xTk6pLL93.jpg',
      release_date: '1932-12-24',
      title: '20,000 Years in Sing Sing',
      video: false,
      vote_average: 6.5,
      vote_count: 31,
    },
    {
      adult: false,
      backdrop_path: '/zlU8BIkgY7E6SMfD3USTWC6bchL.jpg',
      genre_ids: [878, 28, 18, 53],
      id: 119450,
      original_language: 'en',
      original_title: 'Dawn of the Planet of the Apes',
      overview:
        'A group of scientists in San Francisco struggle to stay alive in the aftermath of a plague that is wiping out humanity, while Caesar tries to maintain dominance over his community of intelligent apes.',
      popularity: 107.205,
      poster_path: '/ie14Sm0hRI5f7Te2KIfU64NyCPr.jpg',
      release_date: '2014-06-26',
      title: 'Dawn of the Planet of the Apes',
      video: false,
      vote_average: 7.3,
      vote_count: 9280,
    },
    {
      adult: false,
      backdrop_path: '/xdfMN2nEX7HCv1nYY0iEYYoaTu.jpg',
      genre_ids: [18, 35],
      id: 239562,
      original_language: 'en',
      original_title: 'The Single Moms Club',
      overview:
        "A group of single moms are brought together in the aftermath of an incident at their children's school.",
      popularity: 13.92,
      poster_path: '/cKVwaF5RzibSYbKu4cXh3HAZxDx.jpg',
      release_date: '2014-03-14',
      title: 'The Single Moms Club',
      video: false,
      vote_average: 6,
      vote_count: 119,
    },
    {
      adult: false,
      backdrop_path: '/kOJHfBhGCeBjLjAWw2SHLAztlmf.jpg',
      genre_ids: [35, 10402, 10749],
      id: 872,
      original_language: 'en',
      original_title: "Singin' in the Rain",
      overview: 'In 1927 Hollywood, a silent film production company and cast make a difficult transition to sound.',
      popularity: 18.184,
      poster_path: '/zjrpWniKbzu0zFR5sUI1Ptdfl9y.jpg',
      release_date: '1952-04-09',
      title: "Singin' in the Rain",
      video: false,
      vote_average: 8.2,
      vote_count: 2326,
    },
    {
      adult: false,
      backdrop_path: '/3HnYgndpXpZS0PInke1UYNOCe1r.jpg',
      genre_ids: [18, 28, 80],
      id: 70590,
      original_language: 'hi',
      original_title: 'Singham',
      overview:
        'An honest, small town cop is transferred to a big city that is controlled by a crime boss that he had once humiliated.',
      popularity: 8.732,
      poster_path: '/pggLRaurdWwjqX2vkhKIVQSBjXV.jpg',
      release_date: '2011-07-22',
      title: 'Singham',
      video: false,
      vote_average: 6.9,
      vote_count: 98,
    },
    {
      adult: false,
      backdrop_path: '/qj2xJLxQEgRjm3rbT9ATyLWOWLi.jpg',
      genre_ids: [35],
      id: 81666,
      original_language: 'it',
      original_title: 'Sing Sing',
      overview:
        'Eduardo accidentally discovers that he is adopted. His real father is dying, but before his death he said that his mother was the "Queen of England", failing to clarify that this is the nickname of Italian prostitute. But Eduardo is already rushing to the capital of England...',
      popularity: 4.063,
      poster_path: '/zNyHcK1jypvWmHpI8ykZsyAeNlL.jpg',
      release_date: '1983-10-15',
      title: 'Sing Sing',
      video: false,
      vote_average: 5.4,
      vote_count: 36,
    },
    {
      adult: false,
      backdrop_path: '/j2hc91lyeTSf4efTZgX2h0XlAus.jpg',
      genre_ids: [18, 10749],
      id: 799676,
      original_language: 'te',
      original_title: 'శ్యామ్ సింగ రాయ్',
      overview:
        'A young filmmaker is in a soup right when he’s about to find his footing in the film industry. When he sets out to find an answer, turns out it’s in the past.',
      popularity: 6.781,
      poster_path: '/5C2wGMdwTQDUMIltYnn9qGrOs8w.jpg',
      release_date: '2021-12-24',
      title: 'Shyam Singha Roy',
      video: false,
      vote_average: 7.6,
      vote_count: 7,
    },
    {
      adult: false,
      backdrop_path: '/gvPwKXuG70QaAvk0drCOT8oGC8L.jpg',
      genre_ids: [35, 10402],
      id: 573921,
      original_language: 'en',
      original_title: 'Miranda Sings Live... Your Welcome',
      overview:
        'Viral video star Miranda Sings and her real-world alter ego Colleen Ballinger share the stage in a special packed with music, comedy and "magichinry."',
      popularity: 5.725,
      poster_path: '/7romHZimfMIVzHBUs0VjzcAVxku.jpg',
      release_date: '2019-06-04',
      title: 'Miranda Sings Live... Your Welcome',
      video: false,
      vote_average: 5.7,
      vote_count: 31,
    },
    {
      adult: false,
      backdrop_path: '/zrvhxXRaSeSgzv9f1ZO2PXe9pAv.jpg',
      genre_ids: [28, 35, 80],
      id: 62756,
      original_language: 'ta',
      original_title: 'சிங்கம்',
      overview:
        "The story, set in the backdrop of Nallore, a small town in Thoothukudi District, revolves around Sub-Inspector Durai Singam, a brave and just policeman who serves in his hometown primarily to fulfill his father’s wish. Durai Singam settles every dispute in his town patiently with his words of wisdom and resorts to force only when the situation demands it. Kavya, a city girl who comes on vacation to Nallore, falls in love with Durai Singam. Erimalai, Durai Singam's bumbling colleague and friend, often accompanies him.",
      popularity: 5.573,
      poster_path: '/g7bsLSuEg3FuCY1o7uSzbxMUJLB.jpg',
      release_date: '2010-05-28',
      title: 'Singam',
      video: false,
      vote_average: 6.8,
      vote_count: 48,
    },
  ],
  total_pages: 82,
  total_results: 1621,
}
